# Templates to factorize the service definitions
x-templates:
    worker_base: &worker_base
        build:
            context: services/php
            target: worker
        user: "${USER_ID}:${USER_ID}"
        environment:
            - APP_ENV
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - "../..:/var/www:cached"
        profiles:
            - worker

    redash-service: &redash-service
        image: redash/redash:8.0.0.b32245
        depends_on:
            - redis
        env_file: ./redash.env
        profiles:
            - default

volumes:
    postgres-data: {}
    clickhouse-data: {}
    elasticsearch-data: {}
    grafana-data: {}
    loki-data: {}
    vector-data: {}

services:
    postgres:
        image: postgres:16
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app
            # Create the redash database, the symfony one will be created by castor+symfony
            - POSTGRES_DB=redash
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        profiles:
            - default

    frontend:
        build:
            context: services/php
            target: frontend
            cache_from:
              - "type=registry,ref=${REGISTRY:-}/frontend:cache"
        user: "${USER_ID}:${USER_ID}"
        environment:
            - APP_ENV
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        depends_on:
            postgres:
                condition: service_healthy
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(${PROJECT_DOMAINS})"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.rule=Host(${PROJECT_DOMAINS})"
            # Comment the next line to be able to access frontend via HTTP instead of HTTPS
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.middlewares=redirect-to-https@file"

    # worker_messenger:
    #     <<: *worker_base
    #     command: php -d memory_limit=1G /var/www/bin/console messenger:consume async --memory-limit=128M

    builder:
        build:
            context: services/php
            target: builder
            cache_from:
                - "type=registry,ref=${REGISTRY:-}/builder:cache"
        init: true
        user: "${USER_ID}:${USER_ID}"
        environment:
            - APP_ENV
            # The following list contains the common environment variables exposed by CI platforms
            - GITHUB_ACTIONS
            - CI # Travis CI, CircleCI, Cirrus CI, Gitlab CI, Appveyor, CodeShip, dsari
            - CONTINUOUS_INTEGRATION # Travis CI, Cirrus CI
            - BUILD_NUMBER # Jenkins, TeamCity
            - RUN_ID # TaskCluster, dsari
        volumes:
            - "../..:/var/www:cached"
            - "../../.home:/home/app:cached"
        depends_on:
            - postgres
        profiles:
            - builder

    vector:
        image: timberio/vector:0.36.0-debian
        volumes:
            - ./services/vector/vector.yaml:/etc/vector/vector.yaml
            - vector-data:/var/lib/vector
        expose:
            - "8686"
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-vector.rule=Host(`vector.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-vector.tls=true"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
        volumes:
            - ./services/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - elasticsearch-data:/usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            # https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docker.html#docker-compose-file
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-elasticsearch.rule=Host(`elasticsearch.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-elasticsearch.tls=true"

    kibana:
        image: 'docker.elastic.co/kibana/kibana:7.17.18'
        environment:
            - "SERVER_PUBLICBASEURL=https://kibana.${PROJECT_ROOT_DOMAIN}"
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-kibana.rule=Host(`kibana.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-kibana.tls=true"

    loki:
        image: grafana/loki:2.9.4
        volumes:
            - loki-data:/loki
            - ./services/loki/local-config.yaml:/etc/loki/local-config.yaml
        command: -config.file=/etc/loki/local-config.yaml
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-loki.rule=Host(`loki.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-loki.tls=true"

    grafana:
        image: grafana/grafana:latest
        volumes:
            - grafana-data:/var/lib/grafana
            - ./services/grafana/provisioning:/etc/grafana/provisioning
            - ./services/grafana/dashboards:/etc/grafana/dashboards
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-grafana.rule=Host(`grafana.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-grafana.tls=true"

    clickhouse:
        image: clickhouse/clickhouse-server
        user: "101:101"
        environment:
            CLICKHOUSE_DB: app
            CLICKHOUSE_USER: app
            CLICKHOUSE_PASSWORD: app
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        volumes:
            - "clickhouse-data:/var/lib/clickhouse"
        profiles:
            - default
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-clickhouse.rule=Host(`clickhouse.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-clickhouse.tls=true"

    redash:
        <<: *redash-service
        environment:
            REDASH_WEB_WORKERS: 4
        command: server
        labels:
            - "traefik.enable=true"
            - "project-name=${PROJECT_NAME}"
            - "traefik.http.routers.${PROJECT_NAME}-redash.rule=Host(`redash.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-redash.tls=true"
    redash-scheduler:
        <<: *redash-service
        environment:
            QUEUES: "celery"
            WORKERS_COUNT: 1
        command: scheduler
    redash-scheduled_worker:
        <<: *redash-service
        environment:
            QUEUES: "scheduled_queries,schemas"
            WORKERS_COUNT: 1
        command: worker
    redash-adhoc_worker:
        <<: *redash-service
        environment:
            QUEUES: "queries"
            WORKERS_COUNT: 2
        command: worker
    redis:
        image: redis:7-alpine
        profiles:
            - default
