apiVersion: 1

datasources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      basicAuth: false
      isDefault: true
      version: 1
      editable: false

    - name: ClickHouse
      uid: clickhouse
      type: grafana-clickhouse-datasource
      access: proxy
      orgId: 1
      isDefault: false
      jsonData:
          host: clickhouse
          port: 9000
          defaultDatabase: app
          username: app
          defaultDatasource: true
      secureJsonData:
          password: app
      version: 1
      editable: false
